### ISSUE TITLE
id mapping does not work?

### ISSUE THREAD

**Issue by akralj** [feathersjs/feathers-nedb#11]
Hi,
my frontend requires a "id" to come from the rest service. I tried all sorts of different options to map _id to id, but no avail. i tried it with 1.3 and 2.0.1. I can do it with before and after hooks, but because you put it in the docs i'm assuming it should be handled by feathers-nedb. Is this assumption correct?
here is my code with feathers-nedb 1.3:
```js
# app.js
feathers = require('feathers')
nedb = require('feathers-nedb')
bodyParser = require('body-parser')
hooks = require("feathers-hooks")
# Initialize NEDB CRUD database service
todos = nedb('todos', {id: "id"})
# A Feathers app is the same as an Express app
app = feathers().configure(hooks())
.use(feathers.static('./server/public')) # __dirname
# Add REST API support
app.configure feathers.rest()
# Configure Socket.io real-time APIs
app.configure feathers.socketio()
# Parse HTTP JSON bodies
app.use bodyParser.json()
# Register the todo service
app.use '/todos', todos
# Start the server
app.listen 3333
````

and the result of a get request http://localhost:3333/todos/EMVqs9KyTImCIKyE
```json
{
"_id": "EMVqs9KyTImCIKyE",
"text": "A todo",
"complete": false
}
```

Thanks for your time.

**Comment by daffl** [comment]
That was definitely useless documentation on our part. We added it because all the other adapters allow it as well but it looks like NeDB does not support changing the id property name.

I removed it from the documentation and you are correct with your suggestion to use a hook to do the mapping from `_id` to `id`.

**Comment by akralj** [comment]
excellent. thanks for the clarification.

**Comment by sinedied** [comment]
Is is still true as of today? Because the `id` param is still in the docs, and not working 😕

**Comment by daffl** [comment]
The `id` option is working as documented and tested ([here](https://github.com/feathersjs-ecosystem/feathers-nedb/blob/master/test/index.test.js#L117) and [here](https://github.com/feathersjs-ecosystem/feathers-nedb/blob/master/test/index.test.js#L214)).

**Comment by sinedied** [comment]
I saw the unit tests, but I failed to make it working on a freshly generated project from the CLI:
- setting `id: 'playerId` on my model does not make it work as expected:
  * I can create many objects with the same `playerId` value (not working with `_id`)
  * the `_id` property still exists and set/get along `playerId`
  * `service.get()` does not work with either `playerId` value nor `_id` value (works with `_id` without the `id` remap)

I'm not sure what I could have done wrong since it's pretty straightforward. I ended up remapping in pre/post hooks, but that's frustrating :/

**Comment by sinedied** [comment]
Just to complete with some code:
```js
// Initializes the `scores` service on path `/scores`
const createService = require('feathers-nedb');
const createModel = require('../../models/scores.model');
const hooks = require('./scores.hooks');

module.exports = function (app) {
  const Model = createModel(app);

  const options = {
    Model,
    id: 'playerId'
  };

  // Initialize our service with any options it requires
  app.use('/scores', createService(options));

  // Get our initialized service so that we can register hooks
  const service = app.service('scores');

  service.hooks(hooks);
};
```

**Comment by daffl** [comment]
Just like MongoDB, NeDB needs the `_id` field and there is no way to remove it. Setting `id` will just let the service know to use that as the primary key and does not guarantee that it will be unique. To do that you will have to [create a unique index in NeDB](https://github.com/louischatriot/nedb/wiki/Indexing).

**Comment by sinedied** [comment]
Thanks for the clarification 👍 That might be a useful note on the docs regarding this section!
Will try that, the last remaining point is why `service.get()` wasn't working as expected, but I'll try to find out.

**Comment by sinedied** [comment]
Almost all good, except that trying to create a new entry using a `PUT` or `PATCH` method with the `upsert` option of NeDB enabled does not work anymore:
```
{
  "name": "BadRequest",
  "message": "You can not replace multiple instances. Did you mean 'patch'?",
  "code": 400,
  "className": "bad-request",
  "errors": {}
}
```
The request that was working fine before (by mapping `playerId` to `_id` with a hook)
```
PUT http://localhost:3030/scores
Content-Type: application/json

{
  "playerId": "Pierre",
  "score": 4000
}
```
Any ideas?

**Comment by daffl** [comment]
Please create a new issue with an example.
