### ISSUE TITLE
Support $search

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-nedb#13]

**Comment by marshallswain** [comment]
https://github.com/louischatriot/nedb#operators-lt-lte-gt-gte-in-nin-ne-exists-regex

**Comment by marshallswain** [comment]
Is the syntax for this going to be something like
```
service.find({name: {$search: 'zeld', $options'ig'}})
```
If so, we'll need to make sure we support the logical operators: https://github.com/louischatriot/nedb#logical-operators-or-and-not-where

**Comment by daffl** [comment]
Moved to https://github.com/feathersjs/feathers/issues/334
