### ISSUE TITLE
patch() method doesn't call 'patched' event handler.

### ISSUE THREAD

**Issue by palavrov** [feathersjs/feathers-nedb#39]
It is difficult to extract example from my code but seems that `patched` event handler is not called when patching records with query. Neither the REST API updates web clients when patching.

Could some one please explain me how patch method should work? I'm lost in the code and don't have time to figure it out myself right now in order to debug it deeper. Thanks.

**Comment by marshallswain** [comment]
@palavrov I suspect that this has something to do with something in the app preventing it from happening.  If you do a simple test on a new, fresh service, do you get the same result?

**Comment by palavrov** [comment]
@marshallswain I'm debugging that right now and just find a workaround which seems to work for me, here is the code:
```JS
var removeCableZones = function(zoneId) {
    /* TODO: NeDB patch doesn't call 'patched' event handlers and doesn't
     * notify web clients about patches.

    return cablesService.patch( null, { zoneId: null }, { query: { zoneId: zoneId } });

    */

    return cablesService.find({
        query: {
            zoneId: zoneId
        }
    }).then(function(cables) {
        var actions = [];

        cables = [].concat(cables);

        cables.forEach(function(cable) {
            cable.zoneId = null;

            var action = cablesService.update(cable._id, cable);

            actions.push(action);
        });

        return Promise.all(actions);
    });
};
```

As you can see emulating `patch` with `update` works as expected.

**Comment by marshallswain** [comment]
Latest versions of everything?  `npm outdated` and let me know, please.  I'm going to make a quick test for this right now.

**Comment by palavrov** [comment]
```
palavrov@palavrov-2:~/codigi/ttk/ttk-web$ npm outdated
Package            Current  Wanted        Latest  Location
angular-ui-router    0.3.1   0.3.1  1.0.0-beta.2  TTKweb
feathers             2.0.1   2.0.2         2.0.2  TTKweb
feathers-client      1.5.3   1.6.1         1.6.1  TTKweb
feathers-rest        1.4.4   1.5.0         1.5.0  TTKweb
html-loader          0.4.3   0.4.4         0.4.4  TTKweb
node-fetch           1.6.0   1.6.1         1.6.1  TTKweb
validator            5.6.0   5.7.0         5.7.0  TTKweb
```

**Comment by daffl** [comment]
The problem is probably https://github.com/feathersjs/feathers/issues/393

**Comment by palavrov** [comment]
Indeed, seems exactly the same. Let's close this then.

I was not expecting so quick reaction so:

GUYS, YOU ARE AWESOME !!! FEATHERSJS REALLY ROCKS !!!
