### ISSUE TITLE
Updating documents

### ISSUE THREAD

**Issue by lokenx** [feathersjs/feathers-nedb#5]
Been giving NeDB a try and just found a small improvement for the docs. For the update method it's currently using just the `id` property to select the document, whereas NeDB typically supports any query that `find` also supports.

Some mention of this, and any other slightly changes from the default NeDB behaviour would be helpful!

**Comment by ekryski** [comment]
@lokenx thanks for pointing that out!

We'll prioritize that as a special update to NeDB. We're making sure all the database adapters have a consistent API first. Then we'll circle back to expose some of the specific functionality that each db provides.

As always, feel free to ship a PR as that would help get it in sooner. :smiley:

**Comment by daffl** [comment]
This should work now with the new service functionality using `service.update(null, params)` or `service.patch(null, params)`.
