### ISSUE TITLE
Does feathers-nedb use compactDatafile ?

### ISSUE THREAD

**Issue by quentin-sommer** [feathersjs/feathers-nedb#55]
In NeDB's documentation we can see this:
`The database is automatically compacted (i.e. put back in the one-line-per-document format) every time you load each database within your application.`

I'm wondering if this happens in the lifecycle of a feathers app or just between application restart ?

**Comment by daffl** [comment]
The adapter is just using the NeDB instance you pass as `Model` so whatever you set when creating that database will be used - and when not set it will be the default (when you load the file on application start from what I can see in the docs).

You can set the interval with 

```
const service = app.service('myNeDBservice');
service.Model.persistence.setAutocompactionInterval(interval);
```

On an NeDB service (or the database instance you are passing directly).

**Comment by quentin-sommer** [comment]
Okay thanks :) !
