### ISSUE TITLE
Switch to using NeDB-core

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-nedb#56]
The original NeDB repo and package aren't getting updated anymore, but there is a fork that is well maintained.  We should switch to using it to continue to get updates: https://github.com/nedbhq/nedb-core

**Comment by daffl** [comment]
Somehow we don't seem to have a great track record in picking databases with a solid future 😉

**Comment by corymsmith** [comment]
I was wondering why the repo was redirecting to a fork yesterday.

**Comment by daffl** [comment]
I think I'm going to close this for now. The [nedb-core](https://github.com/nedbhq/nedb-core) repository has 13 GitHub stars with the last commit three months ago and [70 downloads per month on npm](https://www.npmjs.com/package/nedb-core) with the last release two months ago.
