### ISSUE TITLE
Upsert options not working

### ISSUE THREAD

**Issue by guiguan** [feathersjs/feathers-nedb#57]
Using `app.service('myservice').update(id, data, {nedb: {upsert: true}})` doesn't create a new doc if the doc is missing

**Comment by daffl** [comment]
That seems odd, all looks like it should work. Can you post a small breaking test case? It would make it easier to quickly look into.

**Comment by wnxhaja** [comment]
@guiguan if you are doing the query on feathers client then it will not work. https://feathersjs.slack.com/archives/general/p1487381703005830

If you are doing it on server then and still doesn't work then it is worth testing.

**Comment by guiguan** [comment]
@wnxhaja I was querying that on server

**Comment by guiguan** [comment]
@daffl please find the breaking test case here: https://github.com/guiguan/feathers-nedb/blob/master/test/index.test.js#L77

**Comment by nathanstaines** [comment]
I'm not sure why or how but changing `const entry = omit(data, '_id');` to `const entry = data;` seems to fix the issue. There might be a good reason why '_id' is being omitted though?

**Comment by daffl** [comment]
I thought NeDB doesn't let you override the id field. If it does then that is probably the bug.

**Comment by nathanstaines** [comment]
@daffl that's true.

> If the document does not contain an _id field, NeDB will automatically generated one for you (a 16-characters alphanumerical string). The _id of a document, once set, cannot be modified.

However, doing the following would be fine:

``` javascript
app.service('service').update(id, {
  _id: id,
  key: 'value' 
}, {nedb: {upsert: true}});
```

**Comment by 7NT** [comment]
Need help:
when I called:
app.service('users').patch(_id, { status: 0 })

or
const params = {
        query: { email: user.email },
        nedb: { upsert: false }
      }

app.service('users').patch(null, { status: 0 }, params )

both server side and client, it always add a new record in my nedb database, I just want to change that status in that matched record, how can I do it?

TIA

**Comment by daffl** [comment]
Is the record actually showing up twice or are you looking at the NeDB database file? NeDB uses an append-only structure so a record showing up twice in the database file itself is totally normal.

**Comment by 7NT** [comment]
oh, it is appended

can I just modify the record in NeDB, sorry brand new in feathers ...

**Comment by daffl** [comment]
It's already working. If you run `app.service('users').find()` your users should show up as expected.
