### ISSUE TITLE
Can't use modifiers in update method after upgrade to 2.6.1

### ISSUE THREAD

**Issue by exah** [feathersjs/feathers-nedb#59]
### Steps to reproduce

Use update method in nedb service with modifiers (like `$push`, `$pull`, etc.).

```js
projectsService.update('projectId', { $push: { 'data.caption': '' } )
```

Produces error when using feathers-nedb@2.6.1.

```
Error: You cannot mix modifiers and normal fields
```

### System configuration

**Module versions**: 2.6.1

**NodeJS version**: 6.9.5

**Operating System**: macOS 10.12 / docker node:6 container

**Module Loader**: webpack@2.3.2

---

Working normally @`2.6.0`. 
Somehow related to this: https://github.com/feathersjs/feathers-nedb/compare/v2.6.0...v2.6.1#diff-1fdf421c05c1140f6d71444ea2b27638

**Comment by daffl** [comment]
Fixed in v2.6.1

**Comment by exah** [comment]
Thanks!

**Comment by bugss** [comment]
use  nedb  you can not do this
```javascript
yourService.update(id, {
        $inc: {
          good: 1
        },
        createdAt:new Date()
      })
```

property name start with $ and property name not start with $ Can not appear at the same time

so when you set a hooks  like this 

```javascript
exports.before = {
  all: [],
  find: [],
  get: [],
  create: [hooks.setCreatedAt(), hooks.setUpdatedAt()],
  update: [hooks.setUpdatedAt()],
  patch: [],
  remove: []
};
```
and some where  just call the below code  with the before hook above will always exception(You cannot mix modifiers and normal fields)
```javascript
yourService.update(id, {
        $inc: {
          good: 1
        }
      })
```

if you want add timestamp . just remove the hook but set timestampData to true
```javascript
const db = new NeDB({
    filename: path.join(app.get('nedb'), 'posts.db'),
    autoload: true,
    timestampData: true
  });
```

I think it's a good idea to put these into a document

**Comment by marshallswain** [comment]
@bugss absolutely.  Would you mind making a PR to the auk docs?  

It's this page: https://docs.feathersjs.com/v/auk/api/databases/nedb.html
which is here in the repo: https://github.com/feathersjs/feathers-docs/edit/auk/api/databases/nedb.md

**Comment by bugss** [comment]
https://github.com/feathersjs/feathers-docs/pull/457
just add the default config  timestampData: true .   
Should be able to reduce the possibility of reporting this exception

**Comment by pirsplus** [comment]
I don't know if that could help you to solve the issue and pull a new request.

In nedb, if you do this :

```js
db.collection.update({ _id: 'MYID'  },  { key: 'value' , $push: { key: 'value' } }, { returnUpdatedDocs: true, multi: false }, (err, num, doc) => {
  // Error: You cannot mix modifiers and normal fields
})
```

But, if you use 2 modifiers `$set` and `$push` (or whatever)

```js
db.collection.update({ _id: 'MYID'  }, { $set: { key: 'value' }, $push: { key: 'value' } }, { returnUpdatedDocs: true, multi: false }, (err, num, doc) => {
  // will be ok
})
```
The trick is to use `$set` everytime and you could add any modifiers you want.
