### ISSUE TITLE
Get $not support working.

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-nedb#6]
NeDB's $not support is not the same as Mongoose or our Knex implementation. It looks like this:

```js
db.find({ $not: { planet: 'Earth' } }, function (err, docs) {
  // docs contains Mars, Jupiter, Omicron Persei 8
});
```

but should look like this:

```js
db.find({ planet: { $not: 'Earth' } }, function (err, docs) {
  // docs contains Mars, Jupiter, Omicron Persei 8
});
```

**Comment by daffl** [comment]
`$not` isn't implemented anymore in the default query filter (it's `$ne`). This should still work (though not DB independent) right?

**Comment by ekryski** [comment]
Yes it's fine, but I'm just putting it down as an issue to track, as I would like to support it at some point.

**Comment by daffl** [comment]
This has been open for a while and I don't think we should tackle it individually. Maybe when adding $not support to all databases via the service tests. If you want to use NeDBs not you should just be able to use it directly. Closing.
