### ISSUE TITLE
Can't use $select without including id field

### ISSUE THREAD

**Issue by cdelaorden** [feathersjs/feathers-nedb#66]
Hi

`$select` is not working with NeDB as stated in the general query documentation. In order to $select specific fields, you're forced to always include `id`, otherwise the following error is thrown:

```
Error: Can't both keep and omit fields except for _id
    at /Users/carlosdelaorden/Dev/rp/real-property-server/node_modules/nedb/lib/cursor.js:80:73
    at Array.forEach (native)
    at Cursor.project (/Users/carlosdelaorden/Dev/rp/real-property-server/node_modules/nedb/lib/cursor.js:79:8)
...
```

### Steps to reproduce
Create the simplest NeDB service you can, add REST transport and try to $select any fields. The sample in the README should be enough. 

For example, with this service:
```
const app = feathers()
  .use(compress())
  .options('*', cors())
  .use(cors())
  .use(bodyParser.json())
  .use(bodyParser.urlencoded({ extended: true }))
  .configure(rest())
  .configure(services)


function services(){
  this.use('/users', service({ Model: userModel(), paginate: false }))
}

function userModel(){
  return new NeDB({
    filename: path.join('data', 'rp.db'),
    autoload: true
  })
}
```

The following query fails:
`localhost:3000/users/?$select=email`

But this works fine:
`localhost:3000/users/?$select=email&$select=_id`

EDIT: calling it via code works as expected! However, `_id` field is included. The exception is thrown via REST.
```
userService.find({ query: {
  $select: ['email']
}})
.then(res => console.log(res))
```

### Possible cause and solution

The issue is caused by how NeDB handles projections. From their documentation at https://github.com/louischatriot/nedb#projections:

> The syntax is the same as MongoDB: { a: 1, b: 1 } to return only the a and b fields, { a: 0, b: 0 } to omit these two fields. You cannot use both modes at the time, **except for _id which is by default always returned and which you can choose to omit**.

It clearly states that projections by default include id and you should hide it explicitly by sending { _id: 0 }. Looking at the code of this library, this case is not taken into account in `utils/getSelect`:
https://github.com/feathersjs/feathers-nedb/blob/master/src/utils.js#L15

I think it's an easy fix, would be to check if the user has included the `idField` in the select. If it's not, it should be added with `0` so NeDB actually hides it from the result. This means that `getSelect` helper should also have access to the service config to be able to use whatever `idField` the user has chosen.

As stated in my edit, calling the service from code doesn't throw but indeed includes the `idField`. Maybe it's related to the REST query conversion?

If this is not the desired behaviour, then the docs should probably reflect this non-standard query behaviour. Otherwise I'd be happy to contribute the fix if it sounds OK - and add a test for this!  :)

**Comment by daffl** [comment]
Not including the id field if it hasn't been selected is a good call. After writing tests for it in #73 however, I think your actual problem (since it is only cause via REST) is that there is no way to decide if a URL like `localhost:3000/users/?$select=email` should be serialized into an object (`{ $select: 'email' }`) or an array.

You can make that explicit for the query string parser using `localhost:3000/users/?$select[]=email`.

Fix for excluding the id will be released as v2.7.0
