### ISSUE TITLE
how to add validation to nedb?

### ISSUE THREAD

**Issue by akralj** [feathersjs/feathers-nedb#7]
hi all. I am trying to include a validator on post requests and I am pretty lost. I don't know how to add a proper response for the browser. i tried it with hooks and all sorts of others things, but no luck.
I get an exception in the browser with the code below.

```javascript
var apiService, app, bodyParser, errors, feathers, hooks, nedb, port;

feathers = require('feathers');
hooks = require('feathers-hooks');
nedb = require('feathers-nedb');
bodyParser = require('body-parser');
errors = require('feathers-errors').types;

apiService = nedb('api').extend({
  create: function(data, params, cb) {
    var valid;
    if (valid = false) {
      console.log("update", data);
      return this._super(data, params, cb);
    } else {
      //WHAT TO CALL HERE, to get a proper response for the browser
      return cb(new errors.BadRequest("not valid"));
    }
  }
});

app = feathers()
.configure(hooks())
.use(feathers["static"]('./client/dist'))
.configure(feathers.socketio())
.configure(feathers.rest())
.use(bodyParser.json())
.use(bodyParser.urlencoded({extended: true}))
.use('api', apiService)
.use(function(err, req, res, next) {
  console.log(err);
  res.status(404);
  return res.json({
    message: err.message
  });
});

port = 7777;
app.listen(port, function() {
  return console.log('Feathers server listening on port ' + port);
});
```

and the following client request:
```javascript
var data, url;

data = {
  username: "franzl",
  date: new Date(),
  type: "stammtisch"
};

url = "/api";

fetch(url, {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify(data)
}).then(function(res) {
  return console.log(res);
})["catch"](function(err) {
  return console.log(err);
});
```

Feathers in build error messages work fine when trying a GET to a missing id, but not my own validator.

thanks a lot and happy new year.

**Comment by daffl** [comment]
It doesn't look like your extended code would work the way I'd expect it. Did you look at the [guide for using hooks for validation](http://feathersjs.com/learn/validation/)?

A simple extended validator can look like this:

```js
apiService = nedb('api').extend({
  create: function(data, params, cb) {
    if(!data.name) {
      return cb(new errors.BadRequest('Name needs to be provided'));
    }

    return this._super(data, params, cb);
  }
});
```

If you now try to submit data without  a `name` property you should get a `BadRequest` error.

**Comment by akralj** [comment]
merci vielmals :)
that was it. My code was working before too, but I did not read my fetch result properly.

**Comment by ekryski** [comment]
:tada: Glad that worked for you!

@akralj I did also notice that you had `if (valid = false)`. That's gonna cause problems :smile:

**Comment by akralj** [comment]
@ekryski  
(if (valid = false)) of course. but that was only for testing.
