### ISSUE TITLE
NeDB ids are not sequential but ordered alphabetically by default

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-nedb#9]
It looks like the generated ids are not sequential but the default order is alphabetical. This means that items sometimes don't come back in the order they have been created. The workaround to get the tests to pass was to use a counter and sort by that (see https://github.com/feathersjs/feathers-nedb/blob/master/examples/app.js#L11) but I can't believe that there isn't a way to get data in the correct order (`createdAt` didn't work either because sometimes it seemed to create things at the same timestamp).

**Comment by ekryski** [comment]
That's actually the same with mongo. The recommend that if you want guaranteed order then you shouldn't use the `_id` param but rather a counter like you suggest.

It just sort of works most of the time with mongo because of the algorithm they use to generate the ids is based on a timestamp.

**Comment by daffl** [comment]
That's good to know. I guess we don't need to change this for MongoDB but we'll just leave it the way it is then.
